version: '3.8'

services:
  lighttpd:
    build: .
    ports:
      - "8080:80"
    container_name: lighttpd-alpine
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /var/run:noexec,nosuid,size=100m